### ISSUE TITLE
Turn off validation?

### ISSUE THREAD

**Issue by ajdroid** [garythung/torch-lrcn#1]
Hi, I want to reproduce the results from the paper on UCF and test on HMDB51. Can we turn validation off?
I tried using the test splits for validation as well as testing,
got 

> /usr/local/torch/install/bin/luajit: ./util/DataLoader.lua:95: invalid arguments: DoubleTensor nil 
> expected arguments: _DoubleTensor_ double
> stack traceback:
>     [C]: in function 'fill'
>     ./util/DataLoader.lua:95: in function 'nextBatch'
>     train.lua:249: in function 'test'
>     train.lua:183: in function 'train'
>     train.lua:300: in main chunk
>     [C]: in function 'dofile'
>     ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
>     [C]: at 0x00406670

Also, once data is dumped, why does DataLoader take a ton of time everytime I start training (I presume it's checking?)
Great work with this port, btw!

**Comment by garythung** [comment]
@ajdroid Hey, thanks for checking out the repository! I'm sorry, it's been a while since I've looked at this project. There is no easy way or logic to disable validation besides deleting the individual lines. As much as I would like otherwise, I don't have the time or resources to maintain this project.

The DataLoader takes some time to load all the images in memory.

**Comment by pbanavara** [comment]
@ajdroid you can set dumpFrames to 0 to prevent the Dataloader from dumping the frames every time. So every time you restart train.lua won't split the video into frames.
